# Generated by Django 4.0.5 on 2022-06-19 20:45

import RLModels.models
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RLInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, default='projections.csv', max_length=30)),
                ('alias', models.CharField(default=RLModels.models.generateRandom, max_length=30)),
                ('states', models.CharField(max_length=20)),
                ('attributes', django_mysql.models.ListCharField(models.CharField(max_length=15), max_length=96, null=True, size=6)),
                ('bucket_size', models.IntegerField(blank=True, default=200)),
                ('episodes', models.IntegerField(blank=True, default=100)),
                ('epochs', models.IntegerField(blank=True, default=10)),
                ('total_available', models.IntegerField(blank=True, default=1000)),
            ],
            options={
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='uploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='datasets/')),
            ],
            options={
                'ordering': [],
            },
        ),
    ]
